#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FarmOEManager.Resource", IsApplication=true)]

namespace FarmOEManager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Utils.Resource.String.ApplicationName = global::FarmOEManager.Resource.String.ApplicationName;
			global::Utils.Resource.String.OkButton = global::FarmOEManager.Resource.String.OkButton;
			global::Utils.Resource.String.progress_message = global::FarmOEManager.Resource.String.progress_message;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_moreoverflow_normal_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ListItem = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070012
			public const int OrderDate_DateView = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int OrderDate_MemberCountView = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int OrderDate_OrderCountView = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int accountAdminPassword = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int accountFarm = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int accountFirstName = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int accountLastName = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int accountPassword = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int accountTitle = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int adminPasswordTitle = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int farmTitle = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int firstNameTitle = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int gradientItemQty = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int gradientItemText = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int gradientStringText = 2131165197;
			
			// aapt resource value: 0x7f070018
			public const int itemList = 2131165208;
			
			// aapt resource value: 0x7f070003
			public const int lastNameTitle = 2131165187;
			
			// aapt resource value: 0x7f070019
			public const int mainMenuActionBarItem = 2131165209;
			
			// aapt resource value: 0x7f070016
			public const int memberList = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int membersTitle = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int okButton = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int orderDateList = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int passwordTitle = 2131165189;
			
			// aapt resource value: 0x7f07001a
			public const int setAccountMenuItem = 2131165210;
			
			// aapt resource value: 0x7f07000f
			public const int swipeLayout = 2131165199;
			
			// aapt resource value: 0x7f070017
			public const int textView1 = 2131165207;
			
			// aapt resource value: 0x7f07000e
			public const int titleText = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GradientItemView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GradientStringView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListHeader = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int OrderDateView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int OrderSummaryView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ActionBarMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int OkButton = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int about = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int comm_error = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int currentOrderDates = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int farm_prompt = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int invalid_account = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int memberElementText = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int network_error = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int orderElementText = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int orderSummaryTitle = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int progress_message = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int set_account = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int ButtonStyle = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int ListItemStyle1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ListItemStyle2 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int ListViewStyle = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int SmallButtonStyle = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int SmallHeaderStyle = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int SpinnerStyle = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int TitleStyle = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
